#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/log/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/log/html/index.nginx-debian.html
sudo service nginx restart
