#!/usr/bin/env bash
#to configure a new server
config="
frontend your_front_end_name
    bind *:80
    mode http
    default_backend your_backend_name

backend your_backend_name
    balance roundrobin
    server your_server_01_name your_server_01_ip:80 check
    server your_server_02_name your_server_02_ip:80 check
"
